### ISSUE TITLE
Add an open source license?

### ISSUE THREAD

**Issue by amyblais** [swood/mattermost-rand-bot#1]
@swood Thanks for sharing this project! We'd love to use it as part of the Mattermost open source project (https://mattermost.com).

Would you consider adding either an MIT or an Apache 2.0 license?

To do so, in GitHub you can hit "Create new file" and name a file ``LICENSE.txt``. This will prompt GitHub to offer a license template.

If you use a license, it would make it easy to promote your open source project with the Mattermost community.

Thanks kindly for your consideration.

**Comment by swood** [comment]
Hi, @amyblais, done.

**Comment by amyblais** [comment]
Awesome, thank you.
